### ISSUE TITLE
NODE_ENV=development gulp  crashes with ENOSPC error when sublime text 3 is open with the current project

### ISSUE THREAD

**Issue by ranjithnori** [christianalfoni/react-app-boilerplate#20]
`Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at createFsWatchInstance (/var/www/myproject/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:24:15)
    at setFsWatchListener (/var/www/myproject/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:47:19)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/var/www/myproject/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:177:15)
    at EventEmitter.NodeFsHandler._handleFile (/var/www/myproject/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:201:8)
    at EventEmitter.<anonymous> (/var/www/myproject/node_modules/watchify/node_modules/chokidar/lib/nodefs-handler.js:353:12)
    at FSReqWrap.oncomplete (fs.js:95:15)`

**Comment by christianalfoni** [comment]
Hm, that is strange. What OS and node versions are you running on?
