### ISSUE TITLE
gulp test - TypeError: Bad argument

### ISSUE THREAD

**Issue by tukushan** [christianalfoni/react-app-boilerplate#7]
I'm using phantomjs-1.9.8-macosx.zip and get:

```
➜  react-app-boilerplate git:(master) gulp test

/private/tmp/react-app-boilerplate/node_modules/phantomjs/lib/location.js:1
(function (exports, require, module, __filename, __dirname) {
                                                              ^
[14:49:57] Using gulpfile /private/tmp/react-app-boilerplate/gulpfile.js
[14:49:57] Starting 'test'...
TypeError: Bad argument
    at ChildProcess.spawn (child_process.js:933:24)
    at exports.spawn (child_process.js:733:9)
    at Object.exports.execFile (child_process.js:617:15)
    at Transform._transform (/private/tmp/react-app-boilerplate/node_modules/gulp-jasmine2-phantomjs/index.js:32:22)
    at Transform._read (/private/tmp/react-app-boilerplate/node_modules/gulp-jasmine2-phantomjs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/private/tmp/react-app-boilerplate/node_modules/gulp-jasmine2-phantomjs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/private/tmp/react-app-boilerplate/node_modules/gulp-jasmine2-phantomjs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/private/tmp/react-app-boilerplate/node_modules/gulp-jasmine2-phantomjs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/private/tmp/react-app-boilerplate/node_modules/gulp-jasmine2-phantomjs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/private/tmp/react-app-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```

**Comment by christianalfoni** [comment]
Hi @tukushan ,

Hm, that is strange. But any reason you do not use the one installed with `npm install`? I got 1.9.13 running here now and the tests run.
